//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestigeClient_WinForms.PrestigeService_Client {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/PrestigeHost.Model")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PrestigeClient_WinForms.PrestigeService_Client.Check[] ChecksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PrestigeClient_WinForms.PrestigeService_Client.WarehouseWorker[] WarehouseWorkersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PrestigeClient_WinForms.PrestigeService_Client.Check[] Checks {
            get {
                return this.ChecksField;
            }
            set {
                if ((object.ReferenceEquals(this.ChecksField, value) != true)) {
                    this.ChecksField = value;
                    this.RaisePropertyChanged("Checks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodeProduct {
            get {
                return this.CodeProductField;
            }
            set {
                if ((this.CodeProductField.Equals(value) != true)) {
                    this.CodeProductField = value;
                    this.RaisePropertyChanged("CodeProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manufacturer {
            get {
                return this.ManufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerField, value) != true)) {
                    this.ManufacturerField = value;
                    this.RaisePropertyChanged("Manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameProduct {
            get {
                return this.NameProductField;
            }
            set {
                if ((object.ReferenceEquals(this.NameProductField, value) != true)) {
                    this.NameProductField = value;
                    this.RaisePropertyChanged("NameProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PrestigeClient_WinForms.PrestigeService_Client.WarehouseWorker[] WarehouseWorkers {
            get {
                return this.WarehouseWorkersField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseWorkersField, value) != true)) {
                    this.WarehouseWorkersField = value;
                    this.RaisePropertyChanged("WarehouseWorkers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Check", Namespace="http://schemas.datacontract.org/2004/07/PrestigeHost.Model")]
    [System.SerializableAttribute()]
    public partial class Check : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PrestigeClient_WinForms.PrestigeService_Client.Cashier CashierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PrestigeClient_WinForms.PrestigeService_Client.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatePurchaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PrestigeClient_WinForms.PrestigeService_Client.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalSummField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_cashierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_productField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PrestigeClient_WinForms.PrestigeService_Client.Cashier Cashier {
            get {
                return this.CashierField;
            }
            set {
                if ((object.ReferenceEquals(this.CashierField, value) != true)) {
                    this.CashierField = value;
                    this.RaisePropertyChanged("Cashier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PrestigeClient_WinForms.PrestigeService_Client.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatePurchase {
            get {
                return this.DatePurchaseField;
            }
            set {
                if ((this.DatePurchaseField.Equals(value) != true)) {
                    this.DatePurchaseField = value;
                    this.RaisePropertyChanged("DatePurchase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PrestigeClient_WinForms.PrestigeService_Client.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalSumm {
            get {
                return this.TotalSummField;
            }
            set {
                if ((this.TotalSummField.Equals(value) != true)) {
                    this.TotalSummField = value;
                    this.RaisePropertyChanged("TotalSumm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_cashier {
            get {
                return this.id_cashierField;
            }
            set {
                if ((this.id_cashierField.Equals(value) != true)) {
                    this.id_cashierField = value;
                    this.RaisePropertyChanged("id_cashier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_client {
            get {
                return this.id_clientField;
            }
            set {
                if ((this.id_clientField.Equals(value) != true)) {
                    this.id_clientField = value;
                    this.RaisePropertyChanged("id_client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_product {
            get {
                return this.id_productField;
            }
            set {
                if ((this.id_productField.Equals(value) != true)) {
                    this.id_productField = value;
                    this.RaisePropertyChanged("id_product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WarehouseWorker", Namespace="http://schemas.datacontract.org/2004/07/PrestigeHost.Model")]
    [System.SerializableAttribute()]
    public partial class WarehouseWorker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateReceiptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateSaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PrestigeClient_WinForms.PrestigeService_Client.Post PostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PrestigeClient_WinForms.PrestigeService_Client.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_postField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_productField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateReceipt {
            get {
                return this.DateReceiptField;
            }
            set {
                if ((this.DateReceiptField.Equals(value) != true)) {
                    this.DateReceiptField = value;
                    this.RaisePropertyChanged("DateReceipt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSale {
            get {
                return this.DateSaleField;
            }
            set {
                if ((this.DateSaleField.Equals(value) != true)) {
                    this.DateSaleField = value;
                    this.RaisePropertyChanged("DateSale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIO {
            get {
                return this.FIOField;
            }
            set {
                if ((object.ReferenceEquals(this.FIOField, value) != true)) {
                    this.FIOField = value;
                    this.RaisePropertyChanged("FIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PrestigeClient_WinForms.PrestigeService_Client.Post Post {
            get {
                return this.PostField;
            }
            set {
                if ((object.ReferenceEquals(this.PostField, value) != true)) {
                    this.PostField = value;
                    this.RaisePropertyChanged("Post");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PrestigeClient_WinForms.PrestigeService_Client.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_post {
            get {
                return this.id_postField;
            }
            set {
                if ((this.id_postField.Equals(value) != true)) {
                    this.id_postField = value;
                    this.RaisePropertyChanged("id_post");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_product {
            get {
                return this.id_productField;
            }
            set {
                if ((this.id_productField.Equals(value) != true)) {
                    this.id_productField = value;
                    this.RaisePropertyChanged("id_product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cashier", Namespace="http://schemas.datacontract.org/2004/07/PrestigeHost.Model")]
    [System.SerializableAttribute()]
    public partial class Cashier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PrestigeClient_WinForms.PrestigeService_Client.Check[] ChecksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberCashboxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PrestigeClient_WinForms.PrestigeService_Client.Post PostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_postField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PrestigeClient_WinForms.PrestigeService_Client.Check[] Checks {
            get {
                return this.ChecksField;
            }
            set {
                if ((object.ReferenceEquals(this.ChecksField, value) != true)) {
                    this.ChecksField = value;
                    this.RaisePropertyChanged("Checks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberCashbox {
            get {
                return this.NumberCashboxField;
            }
            set {
                if ((this.NumberCashboxField.Equals(value) != true)) {
                    this.NumberCashboxField = value;
                    this.RaisePropertyChanged("NumberCashbox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PrestigeClient_WinForms.PrestigeService_Client.Post Post {
            get {
                return this.PostField;
            }
            set {
                if ((object.ReferenceEquals(this.PostField, value) != true)) {
                    this.PostField = value;
                    this.RaisePropertyChanged("Post");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_post {
            get {
                return this.id_postField;
            }
            set {
                if ((this.id_postField.Equals(value) != true)) {
                    this.id_postField = value;
                    this.RaisePropertyChanged("id_post");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/PrestigeHost.Model")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> CashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PrestigeClient_WinForms.PrestigeService_Client.Check[] ChecksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumberCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Cash {
            get {
                return this.CashField;
            }
            set {
                if ((this.CashField.Equals(value) != true)) {
                    this.CashField = value;
                    this.RaisePropertyChanged("Cash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PrestigeClient_WinForms.PrestigeService_Client.Check[] Checks {
            get {
                return this.ChecksField;
            }
            set {
                if ((object.ReferenceEquals(this.ChecksField, value) != true)) {
                    this.ChecksField = value;
                    this.RaisePropertyChanged("Checks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIO {
            get {
                return this.FIOField;
            }
            set {
                if ((object.ReferenceEquals(this.FIOField, value) != true)) {
                    this.FIOField = value;
                    this.RaisePropertyChanged("FIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberCard {
            get {
                return this.NumberCardField;
            }
            set {
                if ((this.NumberCardField.Equals(value) != true)) {
                    this.NumberCardField = value;
                    this.RaisePropertyChanged("NumberCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Post", Namespace="http://schemas.datacontract.org/2004/07/PrestigeHost.Model")]
    [System.SerializableAttribute()]
    public partial class Post : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PrestigeClient_WinForms.PrestigeService_Client.Cashier[] CashiersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypePostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PrestigeClient_WinForms.PrestigeService_Client.WarehouseWorker[] WarehouseWorkersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PrestigeClient_WinForms.PrestigeService_Client.Cashier[] Cashiers {
            get {
                return this.CashiersField;
            }
            set {
                if ((object.ReferenceEquals(this.CashiersField, value) != true)) {
                    this.CashiersField = value;
                    this.RaisePropertyChanged("Cashiers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypePost {
            get {
                return this.TypePostField;
            }
            set {
                if ((object.ReferenceEquals(this.TypePostField, value) != true)) {
                    this.TypePostField = value;
                    this.RaisePropertyChanged("TypePost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PrestigeClient_WinForms.PrestigeService_Client.WarehouseWorker[] WarehouseWorkers {
            get {
                return this.WarehouseWorkersField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseWorkersField, value) != true)) {
                    this.WarehouseWorkersField = value;
                    this.RaisePropertyChanged("WarehouseWorkers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrestigeService_Client.IPrestigeService")]
    public interface IPrestigeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestigeService/Product", ReplyAction="http://tempuri.org/IPrestigeService/ProductResponse")]
        PrestigeClient_WinForms.PrestigeService_Client.Product[] Product();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPrestigeService/Product", ReplyAction="http://tempuri.org/IPrestigeService/ProductResponse")]
        System.IAsyncResult BeginProduct(System.AsyncCallback callback, object asyncState);
        
        PrestigeClient_WinForms.PrestigeService_Client.Product[] EndProduct(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrestigeServiceChannel : PrestigeClient_WinForms.PrestigeService_Client.IPrestigeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PrestigeClient_WinForms.PrestigeService_Client.Product[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PrestigeClient_WinForms.PrestigeService_Client.Product[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrestigeServiceClient : System.ServiceModel.ClientBase<PrestigeClient_WinForms.PrestigeService_Client.IPrestigeService>, PrestigeClient_WinForms.PrestigeService_Client.IPrestigeService {
        
        private BeginOperationDelegate onBeginProductDelegate;
        
        private EndOperationDelegate onEndProductDelegate;
        
        private System.Threading.SendOrPostCallback onProductCompletedDelegate;
        
        public PrestigeServiceClient() {
        }
        
        public PrestigeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrestigeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrestigeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrestigeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ProductCompletedEventArgs> ProductCompleted;
        
        public PrestigeClient_WinForms.PrestigeService_Client.Product[] Product() {
            return base.Channel.Product();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginProduct(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginProduct(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PrestigeClient_WinForms.PrestigeService_Client.Product[] EndProduct(System.IAsyncResult result) {
            return base.Channel.EndProduct(result);
        }
        
        private System.IAsyncResult OnBeginProduct(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginProduct(callback, asyncState);
        }
        
        private object[] OnEndProduct(System.IAsyncResult result) {
            PrestigeClient_WinForms.PrestigeService_Client.Product[] retVal = this.EndProduct(result);
            return new object[] {
                    retVal};
        }
        
        private void OnProductCompleted(object state) {
            if ((this.ProductCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ProductCompleted(this, new ProductCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ProductAsync() {
            this.ProductAsync(null);
        }
        
        public void ProductAsync(object userState) {
            if ((this.onBeginProductDelegate == null)) {
                this.onBeginProductDelegate = new BeginOperationDelegate(this.OnBeginProduct);
            }
            if ((this.onEndProductDelegate == null)) {
                this.onEndProductDelegate = new EndOperationDelegate(this.OnEndProduct);
            }
            if ((this.onProductCompletedDelegate == null)) {
                this.onProductCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnProductCompleted);
            }
            base.InvokeAsync(this.onBeginProductDelegate, null, this.onEndProductDelegate, this.onProductCompletedDelegate, userState);
        }
    }
}
